workflows:
  ios-capacitor:
    name: Build iOS (Capacitor)
    max_build_duration: 60
    environment:
      node: latest
      xcode: latest
      vars:
        BUNDLE_ID: "com.dogteal.cinephile"  # <-- update if you want
    scripts:
      - name: Install Node dependencies
        script: |
          npm install

      - name: Sync Capacitor iOS platform
        script: |
          npx cap sync ios

      - name: Build iOS archive
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/ios_archive.xcarchive \
            archive \
            DEVELOPMENT_TEAM="" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/ios_archive.xcarchive \
            -exportPath $CM_BUILD_DIR \
